version: "3.9"

services:
  skills-db:
    image: postgres:16
    container_name: skills-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skills_db
    ports:
      - "5433:5432"
    volumes:
      - skills_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  skills_pgdata:
